version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 8085:80
    volumes:
      - ".:/var/www"
      - "./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend

  backend:
    image: php:7.3-fpm
    build:
      context: "."
      dockerfile: "./etc/php/Dockerfile"
    working_dir: "/var/www"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - ADMIN_APP_URL=${ADMIN_APP_URL}
      - ADMIN_APP_PATH=${ADMIN_APP_PATH}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - MAIL_DRIVER=${MAIL_DRIVER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
      - MIX_PUSHER_APP_KEY=${MIX_PUSHER_APP_KEY}
      - MIX_PUSHER_APP_CLUSTER=${MIX_PUSHER_APP_CLUSTER}
      - XDEBUG_CONFIG=remote_host=${HOST_IP}
    volumes:
      - ".:/var/www"
      - "./etc/php/log-stdout.conf:/usr/local/etc/php-fpm.d/zz-log.conf"
      - "./etc/php/upload.ini:/usr/local/etc/php/conf.d/upload.ini"
      - "./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    depends_on:
      - database

  database:
    image: mariadb
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - "./etc/database/data:/var/lib/mysql"
      - "./etc/database:/docker-entrypoint-initdb.d"
